### ISSUE TITLE
Roadmap for react-tile

### ISSUE THREAD

**Issue by davidpfahler** [excellenteasy/react-tile#1]
The idea here is to create a tile component that can render multiple types of content. That includes text, images, but also combine the two (i.e. background images). It should also allow for an icon overlay that indicates the type of content the tile stands for (play icon for a youtube video, photo icon for an instagram image etc.).

# Steps
Inspiration: [Thinking in React](http://facebook.github.io/react/docs/thinking-in-react.html)
* [ ] start with a mock (post here)
* [ ] break the UI into a component hierarchy and post it here
* [ ] Write Dreamcode in README.md and push to feature branch
* [ ] Write unit tests and push to feature branch
* [ ] Make sure, tests are failing
* [ ] Build a static version in React and push to feature branch
* [ ] Identify the minimal (but complete) representation of UI state, if any (post here)
* [ ] if the component has state, some tests should be passing, not all; write more test or rewrite if needed
* [ ] Identify where your state should live, if any
* [ ] Add inverse data flow - almost certainly not needed, but for sake of completeness

**Comment by davidpfahler** [comment]
# Start with a mock
![mock-tile](https://cloud.githubusercontent.com/assets/908242/6269012/f820ccb2-b850-11e4-8dfc-c532f86742a1.png)

**Comment by davidpfahler** [comment]
# Break the UI into a component hierarchy and post it here
![mock-tile-hierarchy](https://cloud.githubusercontent.com/assets/908242/6269024/0c77b7fc-b851-11e4-84e6-5a16a93e8e9c.png)
* Tile (green)
  * SquareBox (purple)
    * FormattedText
  * BottomBar (blue)
    * TimeRelative

Component names aren't great, but it's a start.

**Comment by davidpfahler** [comment]
# Write unit tests and push to feature branch

Harder than expected. **Deferred** until I understand react better. Related question here: [reddit.com/r/react](). I think I'll do something like this:

```javascript
t.deepEqual((
  React.createElement(<div>textcell</div>)
), React.createElement(TextCell))
```

**Comment by davidpfahler** [comment]
# Build a static version in React and push to feature branch
Done. However, it turns out this is all we need, so next two steps are irrelevant here (for now).

Next up: write unit tests for current feature set, then for [dreamcode](DREAMCODE.md) feature set.
